# Generated by Django 5.2.6 on 2025-09-29 05:28

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('rentabilidad', models.FloatField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('clave_elector', models.CharField(blank=True, max_length=13, null=True)),
                ('estatus', models.CharField(choices=[('A', 'Afiliado'), ('D', 'Desafiliado')], default='A', max_length=1)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='contactos.contacto')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactos.seccion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='seccion',
            name='zonales',
            field=models.ManyToManyField(to='contactos.zonal'),
        ),
    ]
