# Generated by Django 5.2.6 on 2025-09-22 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('domicilio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('rentabilidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateField(auto_now=True)),
                ('tipo_relacion', models.CharField(choices=[('block', 'BLOCK'), ('follow', 'FOLLOW')], max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contacto_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibio_relacion', to='contactos.contacto')),
                ('contacto_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inicio_relacion', to='contactos.contacto')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contactos.seccion'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='zonales',
            field=models.ManyToManyField(to='contactos.zonal'),
        ),
    ]
