# Generated by Django 5.2.6 on 2025-10-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
